User.create(username: "Leonardo", email:"leo@tmnt.com", password: "blue")
User.create(username: "Donatello", email:"don@tmnt.com", password: "purple")
User.create(username: "Rafael", email:"raf@tmnt.com", password: "red")
User.create(username: "Michelangelo", email:"mic@tmnt.com", password: "orange")

TakeawayPizza.create(name: "Yard Sale Pizza", address: "184 Hackney Road")
TakeawayPizza.create(name: "Homeslice", address: "374 Old Street")
TakeawayPizza.create(name: "Voodoo Rays", address: "1 Bethnal Green Road")

Review.create(content: "Pizza arrived quickly and piping hot. Possibly the best pizza I've ever had.", user_id: "1", takeaway_pizza_id: "1")
Review.create(content: "Expensive cardboard. Very very very disappointed. Don't go there.", user_id: "1", takeaway_pizza_id: "2")
Review.create(content: "The tomato sauce is great but all the pizzas have far too much cheese.", user_id: "2", takeaway_pizza_id: "2")
Review.create(content: "Tasty, tasty, tasty. Can't recommend it high enough.", user_id: "2", takeaway_pizza_id: "3")
Review.create(content: "I've eaten dogfood that tasted better, avoid unless you're a dog or desperate.", user_id: "3", takeaway_pizza_id: "1")
Review.create(content: "Not the best pizza around however the prices are good and it is open very late when options are limited.", user_id: "3", takeaway_pizza_id: "3")
Review.create(content: "I love the pizzas from this place. Go for the tuna and ice cream supreme and you won't be disappointed.", user_id: "4", takeaway_pizza_id: "2")
Review.create(content: "Cowabunga dude!!!!!!!!!!!", user_id: "4", takeaway_pizza_id: "3")